name: github pages
on:
  push:
    branches:
      - main
      - v2-preview
      - staging
    paths-ignore:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml
  workflow_dispatch:
env:
  hugo_version: '0.157.0'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/cache@v5
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.hugo_version }}
          extended: true
      - name: Build
        run: hugo --gc --minify --logLevel info --cleanDestinationDir --environment production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: "${{ (github.ref_name == 'v2-preview' && 'gh-pages-v2') || (github.ref_name == 'staging' && 'gh-pages-staging') || 'gh-pages' }}"
